### ISSUE TITLE
No Key In Group DM

### ISSUE THREAD

**Issue by NutNutty64** [TheGreenPig/Apate#33]
The recent hotfix seems to have restored the little key icon in direct dms, but my groupchats still have no icon.

**Comment by SuperJumpBros** [comment]
i agree, can someone please fix this? i have to keep closing out of the update popup at the bottom of the screen so that my key icon stays there when in a group dm. i need to keep telling people to not update to the newest version because it breaks the whole thing and doesnt let you send anything with ctrl+enter either.

**Comment by TheGreenPig** [comment]
Fixed in `1.3.4`. Sorry for the inconveniences... Apate got pretty much redesigned a few Updates ago. If you find any other problems, please let me know! 👍
