### ISSUE TITLE
Video/image encryption

### ISSUE THREAD

**Issue by Toczikk** [TheGreenPig/Apate#56]
Why cant the videos or images show up in the encryption box

**Comment by TheGreenPig** [comment]
Apate can only encrypt text because it uses stegcloak. Converting each image and video to some form of text format is not an option since that would take up way too many characters. Image and gif urls will (or should at least) get rendered though, so you can upload your image where and then send the url. If image urls don't get displayed, please make sure the link is a direct link and wait a little bit.
